### ISSUE TITLE
Failing Test 60: roundtrip_autogen.yaml is missing

### ISSUE THREAD

**Issue by borisdaeppen** [dbsrgits/sql-translator#102]
`t/data/roundtrip_autogen.yaml` is missing in `t/60roundtrip.t` on line 91.

I did not find the file in the git history.
Maybe it is still on the authors machine?

**Comment by ilmari** [comment]
It's auto-generated (as indicated by the name) by `perl Makefile.PL` in author mode (i.e. when running from the git checkout, rather than a release tarball). You may need to manually install the dependencies for `SQL::Tanslator::Parser::XML` (`XML::LibXML`) and `SQL::Translator::Producer::YAML` (`YAML`) before running `Makefile.PL`.

**Comment by borisdaeppen** [comment]
Thanks,
(See also https://github.com/dbsrgits/sql-translator/issues/100)
